export const components = [
  {
    id: 1,
    name: "Hero1",
    tag: "hero",
    imgSrc: "/all-components/hero/hero1.png",
    link: "/components/hero#hero1-component",
  },
  {
    id: 2,
    name: "Hero2",
    tag: "hero",
    imgSrc: "/all-components/hero/hero2.png",
    link: "/components/hero#hero2-component",
  },
  {
    id: 3,
    name: "Hero3",
    tag: "hero",
    imgSrc: "/all-components/hero/hero3.png",
    link: "/components/hero#hero3-component",
  },
  {
    id: 4,
    name: "Hero4",
    tag: "hero",
    imgSrc: "/all-components/hero/hero4.png",
    link: "/components/hero#hero4-component",
  },
  {
    id: 5,
    name: "Hero5",
    tag: "hero",
    imgSrc: "/all-components/hero/hero5.png",
    link: "/components/hero#hero5-component",
  },
  {
    id: 6,
    name: "Testimonial1",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial1.png",
    link: "/components/testimonial#testimonial-1",
  },
  {
    id: 7,
    name: "Testimonial2",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial2.png",
    link: "/components/testimonial#testimonial-2",
  },
  {
    id: 8,
    name: "Testimonial3",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial3.png",
    link: "/components/testimonial#testimonial-3",
  },
  {
    id: 9,
    name: "Testimonial4",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial4.png",
    link: "/components/testimonial#testimonial-4",
  },
  {
    id: 10,
    name: "Testimonial5",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial5.png",
    link: "/components/testimonial#testimonial-5",
  },
  {
    id: 11,
    name: "Testimonial6",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial6.png",
    link: "/components/testimonial#testimonial-6",
  },
  {
    id: 12,
    name: "Testimonial7",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial7.png",
    link: "/components/testimonial#testimonial-7",
  },
  {
    id: 13,
    name: "Testimonial8",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial8.png",
    link: "/components/testimonial#testimonial-8",
  },
  {
    id: 14,
    name: "Testimonial9",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial9.png",
    link: "/components/testimonial#testimonial-9",
  },
  {
    id: 15,
    name: "Testimonial10",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial10.png",
    link: "/components/testimonial#testimonial-10",
  },
  {
    id: 16,
    name: "Testimonial11",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial11.png",
    link: "/components/testimonial#testimonial-11",
  },
  {
    id: 17,
    name: "Testimonial12",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial12.png",
    link: "/components/testimonial#testimonial-12",
  },
  {
    id: 18,
    name: "Testimonial13",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial13.png",
    link: "/components/testimonial#testimonial-13",
  },
  {
    id: 19,
    name: "Testimonial14",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial14.png",
    link: "/components/testimonial#testimonial-14",
  },
  {
    id: 20,
    name: "Testimonial15",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial15.png",
    link: "/components/testimonial#testimonial-15",
  },
  {
    id: 21,
    name: "Testimonial16",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial16.png",
    link: "/components/testimonial#testimonial-16",
  },
  {
    id: 22,
    name: "Testimonial17",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial17.png",
    link: "/components/testimonial#testimonial-17",
  },
  {
    id: 23,
    name: "Testimonial18",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial18.png",
    link: "/components/testimonial#testimonial-18",
  },
  {
    id: 24,
    name: "Testimonial19",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial19.png",
    link: "/components/testimonial#testimonial-19",
  },
  {
    id: 25,
    name: "Testimonial20",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial20.png",
    link: "/components/testimonial#testimonial-20",
  },
  {
    id: 26,
    name: "Testimonial21",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial21.png",
    link: "/components/testimonial#testimonial-21",
  },
  {
    id: 27,
    name: "Testimonial22",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial22.png",
    link: "/components/testimonial#testimonial-22",
  },
  {
    id: 28,
    name: "Article1",
    tag: "article",
    imgSrc: "/all-components/article/auraui.png",
    link: "/components/article#aura-ui-article",
  },
  {
    id: 29,
    name: "Connect Sphere",
    tag: "contact",
    imgSrc: "/all-components/contact/connectsphere.png",
    link: "/components/contacts#connectsphere-contact",
  },
  {
    id: 30,
    name: "Light Contact",
    tag: "contact",
    imgSrc: "/all-components/contact/light.png",
    link: "/components/contacts#light-contact-component",
  },
  {
    id: 31,
    name: "Small Contact",
    tag: "contact",
    imgSrc: "/all-components/contact/small.png",
    link: "/components/contacts#small-contact-form",
  },
  {
    id: 32,
    name: "Mini Contact",
    tag: "contact",
    imgSrc: "/all-components/contact/mini.png",
    link: "/components/contacts#mini-contact-form",
  },
  {
    id: 33,
    name: "Simple CTA",
    tag: "cta",
    imgSrc: "/all-components/cta/simple.png",
    link: "/components/cta#simple-cta",
  },
  {
    id: 34,
    name: "Rounded CTA",
    tag: "cta",
    imgSrc: "/all-components/cta/rounded.png",
    link: "/components/cta#rounded-design",
  },
  {
    id: 35,
    name: "Small CTA",
    tag: "cta",
    imgSrc: "/all-components/cta/small.png",
    link: "/components/cta#small-cta",
  },
  {
    id: 36,
    name: "Mini CTA",
    tag: "cta",
    imgSrc: "/all-components/cta/mini.png",
    link: "/components/cta#mini-cta",
  },
  {
    id: 37,
    name: "Connection CTA",
    tag: "cta",
    imgSrc: "/all-components/cta/connection.png",
    link: "/components/cta#connection-cta",
  },
  {
    id: 38,
    name: "Explore Data CTA",
    tag: "cta",
    imgSrc: "/all-components/cta/explore.png",
    link: "/components/cta#explore-data-cta",
  },
  {
    id: 39,
    name: "Connection CTA Secondary",
    tag: "cta",
    imgSrc: "/all-components/cta/connection2.png",
    link: "/components/cta#connection-cta-secondary",
  },
  {
    id: 40,
    name: "One Liner CTA",
    tag: "cta",
    imgSrc: "/all-components/cta/oneliner.png",
    link: "/components/cta#one-liner-cta",
  },
  {
    id: 41,
    name: "Download Option CTA",
    tag: "cta",
    imgSrc: "/all-components/cta/download.png",
    link: "/components/cta#download-option-cta",
  },
  {
    id: 42,
    name: "Blog Grid",
    tag: "blog",
    imgSrc: "/all-components/blog/bloggrid.png",
    link: "/components/blog#blog-grid-component",
  },
  {
    id: 43,
    name: "Question Box Faq",
    tag: "faqs",
    imgSrc: "/all-components/faqs/question.png",
    link: "/components/faqs#question-box-faq-component",
  },
  {
    id: 44,
    name: "Open Faq section",
    tag: "faqs",
    imgSrc: "/all-components/faqs/open.png",
    link: "/components/faqs#open-faq-section-component",
  },
  {
    id: 45,
    name: "Faq section with bg",
    tag: "faqs",
    imgSrc: "/all-components/faqs/section.png",
    link: "/components/faqs#faq-section-with-background-component",
  },
  {
    id: 46,
    name: "Faqs Accordion",
    tag: "faqs",
    imgSrc: "/all-components/faqs/accordion.png",
    link: "/components/faqs#faq-accordion-component",
  },
  {
    id: 47,
    name: "Faqs with Banner",
    tag: "faqs",
    imgSrc: "/all-components/faqs/banner.png",
    link: "/components/faqs#faq-with-banner-component",
  },
  {
    id: 48,
    name: "Features for Payments",
    tag: "feature",
    imgSrc: "/all-components/feature/payments.png",
    link: "/components/feature#features-for-payments-app",
  },
  {
    id: 49,
    name: "Small Feature section",
    tag: "feature",
    imgSrc: "/all-components/feature/small.png",
    link: "/components/feature#small-feature-section",
  },
  {
    id: 50,
    name: "Business Feature",
    tag: "feature",
    imgSrc: "/all-components/feature/business.png",
    link: "/components/feature#business-feature",
  },
  {
    id: 51,
    name: "Business feature secondary",
    tag: "feature",
    imgSrc: "/all-components/feature/business_secondary.png",
    link: "/components/feature#business-feature-secondary",
  },
  {
    id: 52,
    name: "Customer Support",
    tag: "feature",
    imgSrc: "/all-components/feature/customer.png",
    link: "/components/feature#customer-support",
  },
  {
    id: 53,
    name: "Feature1",
    tag: "feature",
    imgSrc: "/all-components/feature/feature1.png",
    link: "/components/feature#feature1-component",
  },
  {
    id: 54,
    name: "Feature2",
    tag: "feature",
    imgSrc: "/all-components/feature/feature2.png",
    link: "/components/feature#feature2-component",
  },
  {
    id: 55,
    name: "Feature3",
    tag: "feature",
    imgSrc: "/all-components/feature/feature3.png",
    link: "/components/feature#feature3-component",
  },
  {
    id: 56,
    name: "Aura Footer ",
    tag: "footer",
    imgSrc: "/all-components/footer/aura.png",
    link: "/components/footer#aura-footer-component",
  },
  {
    id: 57,
    name: "Small Footer ",
    tag: "footer",
    imgSrc: "/all-components/footer/small.png",
    link: "/components/footer#small-footer-component",
  },
  {
    id: 58,
    name: "Light Footer ",
    tag: "footer",
    imgSrc: "/all-components/footer/light.png",
    link: "/components/footer#light-footer-component",
  },
  {
    id: 59,
    name: "Blue Footer ",
    tag: "footer",
    imgSrc: "/all-components/footer/blue.png",
    link: "/components/footer#blue-footer-component",
  },
  {
    id: 60,
    name: "Light Footer Seconday ",
    tag: "footer",
    imgSrc: "/all-components/footer/lightfooter.png",
    link: "/components/footer#light-footer-secondary-component",
  },
  {
    id: 61,
    name: "Showcase Gallery ",
    tag: "gallery",
    imgSrc: "/all-components/gallery/showcase.png",
    link: "/components/gallery#showcase-gallery",
  },
  {
    id: 62,
    name: "Simple Navbar ",
    tag: "navbar",
    imgSrc: "/all-components/header/simple.png",
    link: "/components/header#simple-header",
  },
  {
    id: 63,
    name: "User Account Navbar ",
    tag: "navbar",
    imgSrc: "/all-components/header/useraccount.png",
    link: "/components/header#user-account-navbar",
  },
  {
    id: 64,
    name: "Call to Action Navbar ",
    tag: "navbar",
    imgSrc: "/all-components/header/calltoaction.png",
    link: "/components/header#call-to-action-navbar",
  },
  {
    id: 65,
    name: "Authentication Navbar ",
    tag: "navbar",
    imgSrc: "/all-components/header/authentication.png",
    link: "/components/header#authentication-navbar",
  },
  {
    id: 66,
    name: "Seamless Integration ",
    tag: "integration",
    imgSrc: "/all-components/integration/seamless.png",
    link: "/components/integration#seamless-integration",
  },
  {
    id: 67,
    name: "Trustedlogos Component ",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/trust.png",
    link: "/components/logocloud#trustedbylogos-component",
  },
  {
    id: 68,
    name: "LogoCloud1",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud1.png",
    link: "/components/logocloud#logocloud1-component",
  },
  {
    id: 69,
    name: "LogoCloud2",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud2.png",
    link: "/components/logocloud#logocloud2-component",
  },

  {
    id: 70,
    name: "LogoCloud3",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud3.png",
    link: "/components/logocloud#logocloud3-component",
  },

  {
    id: 71,
    name: "LogoCloud4",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud4.png",
    link: "/components/logocloud#logocloud4-component",
  },
  {
    id: 72,
    name: "LogoCloud5",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud5.png",
    link: "/components/logocloud#logocloud5-component",
  },
  {
    id: 73,
    name: "Newsletter Subscription",
    tag: "newsletter",
    imgSrc: "/all-components/newsletter/subscription.png",
    link: "/components/newsletter#newslettersubscription",
  },
  {
    id: 74,
    name: "Toggle Design",
    tag: "pricing",
    imgSrc: "/all-components/pricing/toggle.png",
    link: "/components/pricing#toggle-design",
  },
  {
    id: 75,
    name: "Card Design",
    tag: "pricing",
    imgSrc: "/all-components/pricing/card.png",
    link: "/components/pricing#card-design",
  },
  {
    id: 76,
    name: "Project Roadmap",
    tag: "roadmap",
    imgSrc: "/all-components/roadmap/roadmap.png",
    link: "/components/roadmap#projectroadmap",
  },
  {
    id: 77,
    name: "Growth Roadmap",
    tag: "roadmap",
    imgSrc: "/all-components/roadmap/growth.png",
    link: "/components/roadmap#growth-roadmap",
  },
  {
    id: 78,
    name: "Complete Roadmap",
    tag: "roadmap",
    imgSrc: "/all-components/roadmap/complete.png",
    link: "/components/roadmap#complete-project-roadmap",
  },
  {
    id: 79,
    name: "Comprehensive Roadmap",
    tag: "roadmap",
    imgSrc: "/all-components/roadmap/comprehensive.png",
    link: "/components/roadmap#comprehensive-roadmap-section",
  },
  {
    id: 80,
    name: "SignIn Card",
    tag: "sign-in",
    imgSrc: "/all-components/sign-in/sign-in1.png",
    link: "/components/sign-in#signin-card-component",
  },
  {
    id: 81,
    name: "Business Signup",
    tag: "sign-up",
    imgSrc: "/all-components/sign-up/sign-up1.png",
    link: "/components/sign-up#business-signup-component",
  },
  {
    id: 82,
    name: "Metricshub Stats",
    tag: "stats",
    imgSrc: "/all-components/stats/metricshub.png",
    link: "/components/stats#metricshub-stats",
  },
  {
    id: 83,
    name: "Achievements Stats",
    tag: "stats",
    imgSrc: "/all-components/stats/achievements.png",
    link: "/components/stats#achievements-stats-section",
  },
  {
    id: 84,
    name: "Growth Impact Stats",
    tag: "stats",
    imgSrc: "/all-components/stats/growth.png",
    link: "/components/stats#growth-impact-stats-section",
  },
  {
    id: 85,
    name: "Solutions Stats",
    tag: "stats",
    imgSrc: "/all-components/stats/solutions.png",
    link: "/components/stats#solutions-stats-component",
  },
  {
    id: 86,
    name: "Verticle Steps",
    tag: "steps",
    imgSrc: "/all-components/steps/verticle.png",
    link: "/components/steps#verticle-steps-component",
  },
  {
    id: 87,
    name: "Visionary Vanguard ",
    tag: "teams",
    imgSrc: "/all-components/teams/visionary.png",
    link: "/components/teams#visionary-vanguard-teams",
  },
  {
    id: 88,
    name: "Exclusive Teams ",
    tag: "teams",
    imgSrc: "/all-components/teams/exclusive.png",
    link: "/components/teams#exclusive-team",
  },
  {
    id: 89,
    name: "Specialist Teams ",
    tag: "teams",
    imgSrc: "/all-components/teams/specialist.png",
    link: "/components/teams#specialist-team",
  },
  {
    id: 90,
    name: "MajnuBhai NFT",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/majnu.png",
    link: "/components/web3/Nft#majnubhai-nft-component",
  },
  {
    id: 91,
    name: "NFT1",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft1.png",
    link: "/components/web3/Nft#nft1-component",
  },
  {
    id: 92,
    name: "NFT2",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft2.png",
    link: "/components/web3/Nft#nft2-component",
  },
  {
    id: 93,
    name: "NFT3",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft3.png",
    link: "/components/web3/Nft#nft3-component",
  },
  {
    id: 94,
    name: "NFT4",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft4.png",
    link: "/components/web3/Nft#nft4-component",
  },
  {
    id: 95,
    name: "NFT5",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft5.png",
    link: "/components/web3/Nft#nft5-component",
  },
];
