export const components = [
	{
		id: 1,
		name: "Hero1",
		tag: "hero",
		imgSrc: "/all-components/hero/hero1.png",
		link: "/components/hero#hero1-component",
	},
	{
		id: 2,
		name: "Hero2",
		tag: "hero",
		imgSrc: "/all-components/hero/hero2.png",
		link: "/components/hero#hero2-component",
	},
	{
		id: 3,
		name: "Hero3",
		tag: "hero",
		imgSrc: "/all-components/hero/hero3.png",
		link: "/components/hero#hero3-component",
	},
	{
		id: 4,
		name: "Hero4",
		tag: "hero",
		imgSrc: "/all-components/hero/hero4.png",
		link: "/components/hero#hero4-component",
	},
	{
		id: 5,
		name: "Hero5",
		tag: "hero",
		imgSrc: "/all-components/hero/hero5.png",
		link: "/components/hero#hero5-component",
	},
	{
		id: 6,
		name: "Testimonial1",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial1.png",
		link: "/components/testimonial#testimonial-1",
	},
	{
		id: 7,
		name: "Testimonial2",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial2.png",
		link: "/components/testimonial#testimonial-2",
	},
	{
		id: 8,
		name: "Testimonial3",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial3.png",
		link: "/components/testimonial#testimonial-3",
	},
	{
		id: 9,
		name: "Testimonial4",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial4.png",
		link: "/components/testimonial#testimonial-4",
	},
	{
		id: 10,
		name: "Testimonial5",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial5.png",
		link: "/components/testimonial#testimonial-5",
	},
	{
		id: 11,
		name: "Testimonial6",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial6.png",
		link: "/components/testimonial#testimonial-6",
	},
	{
		id: 12,
		name: "Testimonial7",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial7.png",
		link: "/components/testimonial#testimonial-7",
	},
	{
		id: 13,
		name: "Testimonial8",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial8.png",
		link: "/components/testimonial#testimonial-8",
	},
	{
		id: 14,
		name: "Testimonial9",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial9.png",
		link: "/components/testimonial#testimonial-9",
	},
	{
		id: 15,
		name: "Testimonial10",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial10.png",
		link: "/components/testimonial#testimonial-10",
	},
	{
		id: 16,
		name: "Testimonial11",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial11.png",
		link: "/components/testimonial#testimonial-11",
	},
	{
		id: 17,
		name: "Testimonial12",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial12.png",
		link: "/components/testimonial#testimonial-12",
	},
	{
		id: 18,
		name: "Testimonial13",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial13.png",
		link: "/components/testimonial#testimonial-13",
	},
	{
		id: 19,
		name: "Testimonial14",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial14.png",
		link: "/components/testimonial#testimonial-14",
	},
	{
		id: 20,
		name: "Testimonial15",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial15.png",
		link: "/components/testimonial#testimonial-15",
	},
	{
		id: 21,
		name: "Testimonial16",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial16.png",
		link: "/components/testimonial#testimonial-16",
	},
	{
		id: 22,
		name: "Testimonial17",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial17.png",
		link: "/components/testimonial#testimonial-17",
	},
	{
		id: 23,
		name: "Testimonial18",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial18.png",
		link: "/components/testimonial#testimonial-18",
	},
	{
		id: 24,
		name: "Testimonial19",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial19.png",
		link: "/components/testimonial#testimonial-19",
	},
	{
		id: 25,
		name: "Testimonial20",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial20.png",
		link: "/components/testimonial#testimonial-20",
	},
	{
		id: 26,
		name: "Testimonial21",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial21.png",
		link: "/components/testimonial#testimonial-21",
	},
	{
		id: 27,
		name: "Testimonial22",
		tag: "testimonial",
		imgSrc: "/all-components/testimonial/testimonial22.png",
		link: "/components/testimonial#testimonial-22",
	},
	{
		id: 28,
		name: "Article1",
		tag: "article",
		imgSrc: "/all-components/article/auraui.png",
    link: "/components/article#aura-ui-article",
	},
	{
		id: 29,
		name: "Connect Sphere",
		tag: "contact",
		imgSrc: "/all-components/contact/connectsphere.png",
    link: "/components/contacts#connectsphere-contact",
	},
	{
		id: 30,
		name: "Light Contact",
		tag: "contact",
		imgSrc: "/all-components/contact/light.png",
    link: "/components/contacts#light-contact-component",
	},
	{
		id: 31,
		name: "Small Contact",
		tag: "contact",
		imgSrc: "/all-components/contact/small.png",
    link: "/components/contacts#small-contact-form",
	},
	{
		id: 32,
		name: "Mini Contact",
		tag: "contact",
		imgSrc: "/all-components/contact/mini.png",
    link: "/components/contacts#mini-contact-form",
	},
	{
		id: 33,
		name: "Simple CTA",
		tag: "cta",
		imgSrc: "/all-components/cta/simple.png",
    link: "/components/cta#simple-cta",
	},
	{
		id: 34,
		name: "Rounded CTA",
		tag: "cta",
		imgSrc: "/all-components/cta/rounded.png",
    link: "/components/cta#rounded-design",
	},
	{
		id: 35,
		name: "Small CTA",
		tag: "cta",
		imgSrc: "/all-components/cta/small.png",
    link: "/components/cta#small-cta",
	},
	{
		id: 36,
		name: "Mini CTA",
		tag: "cta",
		imgSrc: "/all-components/cta/mini.png",
    link: "/components/cta#mini-cta",
	},
	{
		id: 37,
		name: "Connection CTA",
		tag: "cta",
		imgSrc: "/all-components/cta/connection.png",
    link: "/components/cta#connection-cta",
	},
	{
		id: 38,
		name: "Explore Data CTA",
		tag: "cta",
		imgSrc: "/all-components/cta/explore.png",
    link: "/components/cta#explore-data-cta",
	},
	{
		id: 39,
		name: "Connection CTA Secondary",
		tag: "cta",
		imgSrc: "/all-components/cta/connection2.png",
    link: "/components/cta#connection-cta-secondary",
	},
	{
		id: 40,
		name: "One Liner CTA",
		tag: "cta",
		imgSrc: "/all-components/cta/oneliner.png",
    link: "/components/cta#one-liner-cta",
	},
	{
		id: 41,
		name: "Download Option CTA",
		tag: "cta",
		imgSrc: "/all-components/cta/download.png",
    link: "/components/cta#download-option-cta",
	},
]