export const components = [
  {
    id: 1,
    name: "Hero1",
    tag: "hero",
    imgSrc: "/all-components/hero/hero1.png",
    link: "/docs/hero#hero-1",
  },
  {
    id: 2,
    name: "Hero2",
    tag: "hero",
    imgSrc: "/all-components/hero/hero2.png",
    link: "/docs/hero#hero-2",
  },
  {
    id: 3,
    name: "Hero3",
    tag: "hero",
    imgSrc: "/all-components/hero/hero3.png",
    link: "/docs/hero#hero-3",
  },
  {
    id: 4,
    name: "Hero4",
    tag: "hero",
    imgSrc: "/all-components/hero/hero4.png",
    link: "/docs/hero#hero-4",
  },
  {
    id: 5,
    name: "Hero5",
    tag: "hero",
    imgSrc: "/all-components/hero/hero5.png",
    link: "/docs/hero#hero-5",
  },
  {
    id: 6,
    name: "Testimonial1",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial1.png",
    link: "/docs/testimonial#testimonial-1",
  },
  {
    id: 7,
    name: "Testimonial2",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial2.png",
    link: "/docs/testimonial#testimonial-2",
  },
  {
    id: 8,
    name: "Testimonial3",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial3.png",
    link: "/docs/testimonial#testimonial-3",
  },
  {
    id: 9,
    name: "Testimonial4",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial4.png",
    link: "/docs/testimonial#testimonial-4",
  },
  {
    id: 10,
    name: "Testimonial5",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial5.png",
    link: "/docs/testimonial#testimonial-5",
  },
  {
    id: 11,
    name: "Testimonial6",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial6.png",
    link: "/docs/testimonial#testimonial-6",
  },
  {
    id: 12,
    name: "Testimonial7",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial7.png",
    link: "/docs/testimonial#testimonial-7",
  },
  {
    id: 13,
    name: "Testimonial8",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial8.png",
    link: "/docs/testimonial#testimonial-8",
  },
  {
    id: 14,
    name: "Testimonial9",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial9.png",
    link: "/docs/testimonial#testimonial-9",
  },
  {
    id: 15,
    name: "Testimonial10",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial10.png",
    link: "/docs/testimonial#testimonial-10",
  },
  {
    id: 16,
    name: "Testimonial11",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial11.png",
    link: "/docs/testimonial#testimonial-11",
  },
  {
    id: 17,
    name: "Testimonial12",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial12.png",
    link: "/docs/testimonial#testimonial-12",
  },
  {
    id: 18,
    name: "Testimonial13",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial13.png",
    link: "/docs/testimonial#testimonial-13",
  },
  {
    id: 19,
    name: "Testimonial14",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial14.png",
    link: "/docs/testimonial#testimonial-14",
  },
  {
    id: 20,
    name: "Testimonial15",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial15.png",
    link: "/docs/testimonial#testimonial-15",
  },
  {
    id: 21,
    name: "Testimonial16",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial16.png",
    link: "/docs/testimonial#testimonial-16",
  },
  {
    id: 22,
    name: "Testimonial17",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial17.png",
    link: "/docs/testimonial#testimonial-17",
  },
  {
    id: 23,
    name: "Testimonial18",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial18.png",
    link: "/docs/testimonial#testimonial-18",
  },
  {
    id: 24,
    name: "Testimonial19",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial19.png",
    link: "/docs/testimonial#testimonial-19",
  },
  {
    id: 25,
    name: "Testimonial20",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial20.png",
    link: "/docs/testimonial#testimonial-20",
  },
  {
    id: 26,
    name: "Testimonial21",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial21.png",
    link: "/docs/testimonial#testimonial-21",
  },
  {
    id: 27,
    name: "Testimonial22",
    tag: "testimonial",
    imgSrc: "/all-components/testimonial/testimonial22.png",
    link: "/docs/testimonial#testimonial-22",
  },
  {
    id: 28,
    name: "Article1",
    tag: "article",
    imgSrc: "/all-components/article/auraui.png",
    link: "/docs/article#article1",
  },
  {
    id: 29,
    name: "Contact1",
    tag: "contact",
    imgSrc: "/all-components/contact/connectsphere.png",
    link: "/docs/contacts#contact1",
  },
  {
    id: 30,
    name: "Contact2",
    tag: "contact",
    imgSrc: "/all-components/contact/light.png",
    link: "/docs/contacts#contact2",
  },
  {
    id: 31,
    name: "Contact4",
    tag: "contact",
    imgSrc: "/all-components/contact/small.png",
    link: "/docs/contacts#contact4",
  },
  {
    id: 32,
    name: "Contact3",
    tag: "contact",
    imgSrc: "/all-components/contact/mini.png",
    link: "/docs/contacts#contact3",
  },
  {
    id: 33,
    name: "CTA8",
    tag: "cta",
    imgSrc: "/all-components/cta/simple.png",
    link: "/docs/cta#cta8",
  },
  {
    id: 34,
    name: "CTA7",
    tag: "cta",
    imgSrc: "/all-components/cta/rounded.png",
    link: "/docs/cta#cta7",
  },
  {
    id: 35,
    name: "CTA9",
    tag: "cta",
    imgSrc: "/all-components/cta/small.png",
    link: "/docs/cta#cta9",
  },
  {
    id: 36,
    name: "CTA5",
    tag: "cta",
    imgSrc: "/all-components/cta/mini.png",
    link: "/docs/cta#cta5",
  },
  {
    id: 37,
    name: "CTA1",
    tag: "cta",
    imgSrc: "/all-components/cta/connection.png",
    link: "/docs/cta#cta1",
  },
  {
    id: 38,
    name: "CTA4",
    tag: "cta",
    imgSrc: "/all-components/cta/explore.png",
    link: "/docs/cta#cta4",
  },
  {
    id: 39,
    name: "CTA2",
    tag: "cta",
    imgSrc: "/all-components/cta/connection2.png",
    link: "/docs/cta#cta2",
  },
  {
    id: 40,
    name: "CTA6",
    tag: "cta",
    imgSrc: "/all-components/cta/oneliner.png",
    link: "/docs/cta#cta6",
  },
  {
    id: 41,
    name: "CTA3",
    tag: "cta",
    imgSrc: "/all-components/cta/download.png",
    link: "/docs/cta#cta3",
  },
  {
    id: 42,
    name: "Blog1",
    tag: "blog",
    imgSrc: "/all-components/blog/bloggrid.png",
    link: "/docs/blog#blog1",
  },
  {
    id: 43,
    name: "Faqs5",
    tag: "faqs",
    imgSrc: "/all-components/faqs/question.png",
    link: "/docs/faqs#faqs5",
  },
  {
    id: 44,
    name: "Faqs4",
    tag: "faqs",
    imgSrc: "/all-components/faqs/open.png",
    link: "/docs/faqs#faqs4",
  },
  {
    id: 45,
    name: "Faqs2",
    tag: "faqs",
    imgSrc: "/all-components/faqs/section.png",
    link: "/docs/faqs#faqs2",
  },
  {
    id: 46,
    name: "Faqs1 ",
    tag: "faqs",
    imgSrc: "/all-components/faqs/accordion.png",
    link: "/docs/faqs#faqs1",
  },
  {
    id: 47,
    name: "Faqs3",
    tag: "faqs",
    imgSrc: "/all-components/faqs/banner.png",
    link: "/docs/faqs#faqs3",
  },
  {
    id: 48,
    name: "Feature13",
    tag: "feature",
    imgSrc: "/all-components/feature/payments.png",
    link: "/docs/feature#feature13",
  },
  {
    id: 49,
    name: "Feature15",
    tag: "feature",
    imgSrc: "/all-components/feature/small.png",
    link: "/docs/feature#feature15",
  },
  {
    id: 50,
    name: "Feature11",
    tag: "feature",
    imgSrc: "/all-components/feature/business.png",
    link: "/docs/feature#feature11",
  },
  {
    id: 51,
    name: "Feature12",
    tag: "feature",
    imgSrc: "/all-components/feature/business_secondary.png",
    link: "/docs/feature#feature12",
  },
  {
    id: 52,
    name: "Feature14",
    tag: "feature",
    imgSrc: "/all-components/feature/customer.png",
    link: "/docs/feature#feature14",
  },
  {
    id: 53,
    name: "Feature1",
    tag: "feature",
    imgSrc: "/all-components/feature/feature1.png",
    link: "/docs/feature#feature1-component",
  },
  {
    id: 54,
    name: "Feature2",
    tag: "feature",
    imgSrc: "/all-components/feature/feature2.png",
    link: "/docs/feature#feature2-component",
  },
  {
    id: 55,
    name: "Feature3",
    tag: "feature",
    imgSrc: "/all-components/feature/feature3.png",
    link: "/docs/feature#feature3-component",
  },
  {
    id: 56,
    name: "Footer1 ",
    tag: "footer",
    imgSrc: "/all-components/footer/aura.png",
    link: "/docs/footer#footer1",
  },
  {
    id: 57,
    name: "Footer5 ",
    tag: "footer",
    imgSrc: "/all-components/footer/small.png",
    link: "/docs/footer#footer5",
  },
  {
    id: 58,
    name: "Footer3 ",
    tag: "footer",
    imgSrc: "/all-components/footer/light.png",
    link: "/docs/footer#footer3",
  },
  {
    id: 59,
    name: "Footer2 ",
    tag: "footer",
    imgSrc: "/all-components/footer/blue.png",
    link: "/docs/footer#footer2",
  },
  {
    id: 60,
    name: "Footer4 ",
    tag: "footer",
    imgSrc: "/all-components/footer/lightfooter.png",
    link: "/docs/footer#footer4",
  },
  {
    id: 61,
    name: "Gallery1 ",
    tag: "gallery",
    imgSrc: "/all-components/gallery/showcase.png",
    link: "/docs/gallery#gallery1",
  },
  {
    id: 62,
    name: "Navbar3 ",
    tag: "navbar",
    imgSrc: "/all-components/header/simple.png",
    link: "/docs/header#header3",
  },
  {
    id: 63,
    name: "User Account Navbar ",
    tag: "navbar",
    imgSrc: "/all-components/header/useraccount.png",
    link: "/docs/header#user-account-navbar",
  },
  {
    id: 64,
    name: "Navbar2 ",
    tag: "navbar",
    imgSrc: "/all-components/header/calltoaction.png",
    link: "/docs/header#header2",
  },
  {
    id: 65,
    name: "Navbar1 ",
    tag: "navbar",
    imgSrc: "/all-components/header/authentication.png",
    link: "/docs/header#header1",
  },
  {
    id: 66,
    name: "Integration1 ",
    tag: "integration",
    imgSrc: "/all-components/integration/seamless.png",
    link: "/docs/integration#integration1",
  },
  {
    id: 67,
    name: "LogoCloud1 ",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud1.png",
    link: "/docs/logocloud#logocloud1",
  },
  {
    id: 68,
    name: "LogoCloud2",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud2.png",
    link: "/docs/logocloud#logocloud2",
  },
  {
    id: 69,
    name: "LogoCloud3",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud3.png",
    link: "/docs/logocloud#logocloud3",
  },

  {
    id: 70,
    name: "LogoCloud4",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud4.png",
    link: "/docs/logocloud#logocloud4",
  },

  {
    id: 71,
    name: "LogoCloud5",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud5.png",
    link: "/docs/logocloud#logocloud5",
  },
  {
    id: 72,
    name: "LogoCloud6",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud6.png",
    link: "/docs/logocloud#logocloud6",
  },
  {
    id: 73,
    name: "NewsLetter1",
    tag: "newsletter",
    imgSrc: "/all-components/newsletter/subscription.png",
    link: "/docs/newsletter#newsletter1",
  },
  {
    id: 74,
    name: "Prcing 17",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing17.png",
    link: "/docs/pricing#pricing-17",
  },
  {
    id: 75,
    name: "Prcing 16",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing16.png",
    link: "/docs/pricing#pricing-16",
  },
  {
    id: 76,
    name: "Roadmap4",
    tag: "roadmap",
    imgSrc: "/all-components/roadmap/roadmap.png",
    link: "/docs/roadmap#roadmap4",
  },
  {
    id: 77,
    name: "Roadmap3",
    tag: "roadmap",
    imgSrc: "/all-components/roadmap/growth.png",
    link: "/docs/roadmap#roadmap3",
  },
  {
    id: 78,
    name: "Roadmap1",
    tag: "roadmap",
    imgSrc: "/all-components/roadmap/complete.png",
    link: "/docs/roadmap#roadmap1",
  },
  {
    id: 79,
    name: "Roadmap2",
    tag: "roadmap",
    imgSrc: "/all-components/roadmap/comprehensive.png",
    link: "/docs/roadmap#roadmap2",
  },
  {
    id: 80,
    name: "SignIn Card",
    tag: "sign-in",
    imgSrc: "/all-components/sign-in/sign-in1.png",
    link: "/docs/sign-in#signin-card-component",
  },
  {
    id: 81,
    name: "Business Signup",
    tag: "sign-up",
    imgSrc: "/all-components/sign-up/sign-up1.png",
    link: "/docs/sign-up#business-signup-component",
  },
  {
    id: 82,
    name: "Stats3",
    tag: "stats",
    imgSrc: "/all-components/stats/metricshub.png",
    link: "/docs/stats#stats3",
  },
  {
    id: 83,
    name: "Stats1",
    tag: "stats",
    imgSrc: "/all-components/stats/achievements.png",
    link: "/docs/stats#stats1",
  },
  {
    id: 84,
    name: "Stats2",
    tag: "stats",
    imgSrc: "/all-components/stats/growth.png",
    link: "/docs/stats#stats",
  },
  {
    id: 85,
    name: "Stats4",
    tag: "stats",
    imgSrc: "/all-components/stats/solutions.png",
    link: "/docs/stats#stats4",
  },
  {
    id: 86,
    name: "Steps1",
    tag: "steps",
    imgSrc: "/all-components/steps/verticle.png",
    link: "/docs/steps#steps1",
  },
  {
    id: 87,
    name: "Team3 ",
    tag: "teams",
    imgSrc: "/all-components/teams/visionary.png",
    link: "/docs/teams#team3",
  },
  {
    id: 88,
    name: "Team1 ",
    tag: "teams",
    imgSrc: "/all-components/teams/exclusive.png",
    link: "/docs/teams#team1",
  },
  {
    id: 89,
    name: "Team2 ",
    tag: "teams",
    imgSrc: "/all-components/teams/specialist.png",
    link: "/docs/teams#team2",
  },
  {
    id: 90,
    name: "NFT14",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft14.png",
    link: "/docs/web3/Nft#nft14",
  },
  {
    id: 91,
    name: "NFT1",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft1.png",
    link: "/docs/web3/Nft#nft1",
  },
  {
    id: 92,
    name: "NFT2",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft2.png",
    link: "/docs/web3/Nft#nft2",
  },
  {
    id: 93,
    name: "NFT3",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft3.png",
    link: "/docs/web3/Nft#nft3",
  },
  {
    id: 94,
    name: "NFT4",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft4.png",
    link: "/docs/web3/Nft#nft4",
  },
  {
    id: 95,
    name: "NFT5",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft5.png",
    link: "/docs/web3/Nft#nft5",
  },
  {
    id: 96,
    name: "Feature4",
    tag: "feature",
    imgSrc: "/all-components/feature/feature4.png",
    link: "/docs/feature#feature4-component",
  },
  {
    id: 97,
    name: "Feature5",
    tag: "feature",
    imgSrc: "/all-components/feature/feature5.png",
    link: "/docs/feature#feature5-component",
  },
  {
    id: 98,
    name: "Feature6",
    tag: "feature",
    imgSrc: "/all-components/feature/feature6.png",
    link: "/docs/feature#feature6-component",
  },
  {
    id: 99,
    name: "Feature7",
    tag: "feature",
    imgSrc: "/all-components/feature/feature7.png",
    link: "/docs/feature#feature7-component",
  },
  {
    id: 100,
    name: "Feature8",
    tag: "feature",
    imgSrc: "/all-components/feature/feature8.png",
    link: "/docs/feature#feature8-component",
  },
  {
    id: 101,
    name: "Feature9",
    tag: "feature",
    imgSrc: "/all-components/feature/feature9.png",
    link: "/docs/feature#feature9-component",
  },
  {
    id: 102,
    name: "Feature10",
    tag: "feature",
    imgSrc: "/all-components/feature/feature10.png",
    link: "/docs/feature#feature10-component",
  },
  {
    id: 103,
    name: "Pricing1",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing1.png",
    link: "/docs/pricing#pricing-1",
  },
  {
    id: 104,
    name: "Pricing2",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing2.png",
    link: "/docs/pricing#pricing-2",
  },
  {
    id: 105,
    name: "Pricing3",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing3.png",
    link: "/docs/pricing#pricing-3",
  },
  {
    id: 106,
    name: "Pricing4",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing4.png",
    link: "/docs/pricing#pricing-4",
  },
  {
    id: 107,
    name: "Pricing5",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing5.png",
    link: "/docs/pricing#pricing-5",
  },
  {
    id: 108,
    name: "Pricing6",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing6.png",
    link: "/docs/pricing#pricing-6",
  },
  {
    id: 109,
    name: "Pricing7",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing7.png",
    link: "/docs/pricing#pricing-7",
  },
  {
    id: 110,
    name: "Pricing8",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing8.png",
    link: "/docs/pricing#pricing-8",
  },
  {
    id: 111,
    name: "Pricing9",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing9.png",
    link: "/docs/pricing#pricing-9",
  },
  {
    id: 112,
    name: "Pricing10",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing10.png",
    link: "/docs/pricing#pricing-10",
  },
  {
    id: 113,
    name: "Pricing11",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing11.png",
    link: "/docs/pricing#pricing-11",
  },
  {
    id: 114,
    name: "Pricing12",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing12.png",
    link: "/docs/pricing#pricing-12",
  },
  {
    id: 115,
    name: "Pricing13",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing13.png",
    link: "/docs/pricing#pricing-13",
  },
  {
    id: 116,
    name: "Pricing14",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing14.png",
    link: "/docs/pricing#pricing-14",
  },
  {
    id: 118,
    name: "Pricing15",
    tag: "pricing",
    imgSrc: "/all-components/pricing/pricing15.png",
    link: "/docs/pricing#pricing-15",
  },
  {
    id: 119,
    name: "Hero6",
    tag: "hero",
    imgSrc: "/all-components/hero/hero6.png",
    link: "/docs/hero#hero-6",
  },
  {
    id: 120,
    name: "Hero7",
    tag: "hero",
    imgSrc: "/all-components/hero/hero7.png",
    link: "/docs/hero#hero-7",
  },
  {
    id: 121,
    name: "Hero8",
    tag: "hero",
    imgSrc: "/all-components/hero/hero8.png",
    link: "/docs/hero#hero-8",
  },
  {
    id: 122,
    name: "Hero9",
    tag: "hero",
    imgSrc: "/all-components/hero/hero9.png",
    link: "/docs/hero#hero-9",
  },
  {
    id: 123,
    name: "Hero10",
    tag: "hero",
    imgSrc: "/all-components/hero/hero10.png",
    link: "/docs/hero#hero-10",
  },
  {
    id: 124,
    name: "Hero11",
    tag: "hero",
    imgSrc: "/all-components/hero/hero11.png",
    link: "/docs/hero#hero-11",
  },
  {
    id: 125,
    name: "Hero12",
    tag: "hero",
    imgSrc: "/all-components/hero/hero12.png",
    link: "/docs/hero#hero-12",
  },
  {
    id: 126,
    name: "Hero13",
    tag: "hero",
    imgSrc: "/all-components/hero/hero13.png",
    link: "/docs/hero#hero-13",
  },
  {
    id: 127,
    name: "Hero14",
    tag: "hero",
    imgSrc: "/all-components/hero/hero14.png",
    link: "/docs/hero#hero-14",
  },
  {
    id: 128,
    name: "Hero15",
    tag: "hero",
    imgSrc: "/all-components/hero/hero15.png",
    link: "/docs/hero#hero-15",
  },
  {
    id: 129,
    name: "Hero16",
    tag: "hero",
    imgSrc: "/all-components/hero/hero16.png",
    link: "/docs/hero#hero-16",
  },
  {
    id: 130,
    name: "Hero17",
    tag: "hero",
    imgSrc: "/all-components/hero/hero17.png",
    link: "/docs/hero#hero-17",
  },
  {
    id: 131,
    name: "Hero18",
    tag: "hero",
    imgSrc: "/all-components/hero/hero18.png",
    link: "/docs/hero#hero-18",
  },
  {
    id: 132,
    name: "Hero19",
    tag: "hero",
    imgSrc: "/all-components/hero/hero19.png",
    link: "/docs/hero#hero-19",
  },
  {
    id: 133,
    name: "Hero20",
    tag: "hero",
    imgSrc: "/all-components/hero/hero20.png",
    link: "/docs/hero#hero-20",
  },
  {
    id: 134,
    name: "Hero21",
    tag: "hero",
    imgSrc: "/all-components/hero/hero21.png",
    link: "/docs/hero#hero-21",
  },
  {
    id: 135,
    name: "Hero22",
    tag: "hero",
    imgSrc: "/all-components/hero/hero22.png",
    link: "/docs/hero#hero-22",
  },
  {
    id: 136,
    name: "Hero23",
    tag: "hero",
    imgSrc: "/all-components/hero/hero23.png",
    link: "/docs/hero#hero-23",
  },
  {
    id: 137,
    name: "Hero24",
    tag: "hero",
    imgSrc: "/all-components/hero/hero24.png",
    link: "/docs/hero#hero-24",
  },
  {
    id: 138,
    name: "Hero25",
    tag: "hero",
    imgSrc: "/all-components/hero/hero25.png",
    link: "/docs/hero#hero-25",
  },
  {
    id: 139,
    name: "Hero26",
    tag: "hero",
    imgSrc: "/all-components/hero/hero26.png",
    link: "/docs/hero#hero-26",
  },
  {
    id: 140,
    name: "Hero27",
    tag: "hero",
    imgSrc: "/all-components/hero/hero27.png",
    link: "/docs/hero#hero-27",
  },
  {
    id: 141,
    name: "Hero28",
    tag: "hero",
    imgSrc: "/all-components/hero/hero28.png",
    link: "/docs/hero#hero-28",
  },
  {
    id: 142,
    name: "Hero29",
    tag: "hero",
    imgSrc: "/all-components/hero/hero29.png",
    link: "/docs/hero#hero-29",
  },
  {
    id: 143,
    name: "Hero30",
    tag: "hero",
    imgSrc: "/all-components/hero/hero30.png",
    link: "/docs/hero#hero-30",
  },
  {
    id: 144,
    name: "Hero31",
    tag: "hero",
    imgSrc: "/all-components/hero/hero31.png",
    link: "/docs/hero#hero-31",
  },
  {
    id: 145,
    name: "Hero32",
    tag: "hero",
    imgSrc: "/all-components/hero/hero32.png",
    link: "/docs/hero#hero-32",
  },
  {
    id: 146,
    name: "Feature16",
    tag: "feature",
    imgSrc: "/all-components/feature/feature16.png",
    link: "/docs/feature#feature16",
  },
  {
    id: 147,
    name: "Feature17",
    tag: "feature",
    imgSrc: "/all-components/feature/feature17.png",
    link: "/docs/feature#feature17",
  },
  {
    id: 148,
    name: "Feature18",
    tag: "feature",
    imgSrc: "/all-components/feature/feature18.png",
    link: "/docs/feature#feature18",
  },
  {
    id: 149,
    name: "Feature19",
    tag: "feature",
    imgSrc: "/all-components/feature/feature19.png",
    link: "/docs/feature#feature19",
  },
  {
    id: 150,
    name: "Feature20",
    tag: "feature",
    imgSrc: "/all-components/feature/feature20.png",
    link: "/docs/feature#feature20",
  },

  {
    id: 151,
    name: "Hero33",
    tag: "hero",
    imgSrc: "/all-components/hero/hero33.png",
    link: "/docs/hero#hero-33",
  },
  {
    id: 152,
    name: "NFT6",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft6.png",
    link: "/docs/web3/Nft#nft1",
  },
  {
    id: 153,
    name: "NFT7",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft7.png",
    link: "/docs/web3/Nft#nft7",
  },
  {
    id: 154,
    name: "NFT8",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft8.png",
    link: "/docs/web3/Nft#nft8",
  },
  {
    id: 155,
    name: "NFT9",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft9.png",
    link: "/docs/web3/Nft#nft9",
  },
  {
    id: 156,
    name: "NFT10",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft10.png",
    link: "/docs/web3/Nft#nft10",
  },
  {
    id: 157,
    name: "NFT11",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft11.png",
    link: "/docs/web3/Nft#nft11",
  },
  {
    id: 158,
    name: "NFT12",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft12.png",
    link: "/docs/web3/Nft#nft12",
  },
  {
    id: 159,
    name: "NFT13",
    tag: "nft",
    imgSrc: "/all-components/web3/nft/nft13.png",
    link: "/docs/web3/Nft#nft13",
  },
  {
    id: 160,
    name: "LogoCloud7",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud7.png",
    link: "/docs/logocloud#logocloud7",
  },
  {
    id: 161,
    name: "LogoCloud7",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud7.png",
    link: "/docs/logocloud#logocloud7",
  },
  {
    id: 162,
    name: "LogoCloud8",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud8.png",
    link: "/docs/logocloud#logocloud8",
  },
  {
    id: 163,
    name: "LogoCloud9",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud9.png",
    link: "/docs/logocloud#logocloud9",
  },
  {
    id: 164,
    name: "LogoCloud10",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud10.png",
    link: "/docs/logocloud#logocloud10",
  },
  {
    id: 165,
    name: "LogoCloud11",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud11.png",
    link: "/docs/logocloud#logocloud11",
  },
  {
    id: 166,
    name: "LogoCloud12",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud12.png",
    link: "/docs/logocloud#logocloud12",
  },
  {
    id: 167,
    name: "LogoCloud13",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud13.png",
    link: "/docs/logocloud#logocloud13",
  },
  {
    id: 168,
    name: "LogoCloud14",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud14.png",
    link: "/docs/logocloud#logocloud14",
  },
  {
    id: 169,
    name: "LogoCloud15",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud15.png",
    link: "/docs/logocloud#logocloud15",
  },
  {
    id: 170,
    name: "LogoCloud16",
    tag: "logocloud",
    imgSrc: "/all-components/logocloud/logocloud16.png",
    link: "/docs/logocloud#logocloud16",
  },
];
